### ISSUE TITLE
Error while indexing

### ISSUE THREAD

**Issue by npicado** [ishchenko/idea-nginx#10]
Error while indexing
X:\XXX\XXX\app_backend.conf
To reindex this file IDEA has to be restarted: 847
java.lang.ArrayIndexOutOfBoundsException: 847
    at com.intellij.util.text.CharArrayCharSequence.charAt(CharArrayCharSequence.java:48)
    at net.ishchenko.idea.nginx.lexer._NginxLexer.advance(_NginxLexer.java:500)
    at com.intellij.lexer.FlexAdapter.locateToken(FlexAdapter.java:93)
    at com.intellij.lexer.FlexAdapter.getTokenType(FlexAdapter.java:57)
    at com.intellij.openapi.editor.ex.util.LexerEditorHighlighter.a(LexerEditorHighlighter.java:311)
    at com.intellij.openapi.editor.ex.util.LexerEditorHighlighter.setText(LexerEditorHighlighter.java:292)
    at com.intellij.psi.impl.cache.impl.id.PlatformIdTableBuilding$TokenSetTodoIndexer.map(PlatformIdTableBuilding.java:172)
    at com.intellij.psi.impl.cache.impl.id.PlatformIdTableBuilding$TokenSetTodoIndexer.map(PlatformIdTableBuilding.java:149)
    at com.intellij.psi.impl.cache.impl.todo.TodoIndex$4.map(TodoIndex.java:107)
    at com.intellij.psi.impl.cache.impl.todo.TodoIndex$4.map(TodoIndex.java:99)
    at com.intellij.util.indexing.MapReduceIndex.update(MapReduceIndex.java:219)
    at com.intellij.util.indexing.FileBasedIndexImpl$25.run(FileBasedIndexImpl.java:1759)
    at com.intellij.openapi.progress.impl.ProgressManagerImpl.executeNonCancelableSection(ProgressManagerImpl.java:137)
    at com.intellij.util.indexing.FileBasedIndexImpl.updateSingleIndex(FileBasedIndexImpl.java:1755)
    at com.intellij.util.indexing.FileBasedIndexImpl.indexFileContent(FileBasedIndexImpl.java:1719)
    at com.intellij.util.indexing.FileBasedIndexImpl$ChangedFilesCollector.processFileImpl(FileBasedIndexImpl.java:2181)
    at com.intellij.util.indexing.FileBasedIndexImpl$ChangedFilesCollector.access$3100(FileBasedIndexImpl.java:1840)
    at com.intellij.util.indexing.FileBasedIndexImpl.processRefreshedFile(FileBasedIndexImpl.java:1683)
    at com.intellij.util.indexing.FileBasedIndexProjectHandler$RefreshCacheUpdater.processFile(FileBasedIndexProjectHandler.java:131)
    at com.intellij.openapi.project.CacheUpdateSession.processFile(CacheUpdateSession.java:102)
    at com.intellij.openapi.project.CacheUpdateRunner$MyRunnable$1.run(CacheUpdateRunner.java:231)
    at com.intellij.openapi.project.CacheUpdateRunner$MyRunnable.run(CacheUpdateRunner.java:240)
    at com.intellij.openapi.project.CacheUpdateRunner$4.run(CacheUpdateRunner.java:265)
    at com.intellij.openapi.application.impl.ApplicationImpl$8.run(ApplicationImpl.java:454)
    at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:471)
    at java.util.concurrent.FutureTask$Sync.innerRun(FutureTask.java:334)
    at java.util.concurrent.FutureTask.run(FutureTask.java:166)
    at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1110)
    at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:603)
    at java.lang.Thread.run(Thread.java:722)
    at com.intellij.openapi.application.impl.ApplicationImpl$1$1.run(ApplicationImpl.java:152)

**Comment by aikomastboom** [comment]
+1
```
Error while indexing /Users/AikoM/Development/cxp-ops/roles/sinopia/templates/npm_dispatcher.nginx.conf
To reindex this file IDEA has to be restarted: 0
java.lang.ArrayIndexOutOfBoundsException: 0
	at com.intellij.util.text.CharArrayCharSequence.charAt(CharArrayCharSequence.java:48)
```
```
server {
    listen          80;
    server_name     {{ sinopia_hostname }}.{{ domainname }};
    access_log      /var/log/nginx/{{ sinopia_hostname }}.{{ domainname }}.access.log;
    error_log       /var/log/nginx/{{ sinopia_hostname }}.{{ domainname }}.error.log;

    large_client_header_buffers 8 64k;

    location / {

        proxy_pass http://{{ sinopia_hostname }}.local:80;
        proxy_next_upstream error timeout invalid_header http_500 http_502 http_503 http_504;

        proxy_redirect              off;
        proxy_set_header            Host            {{ sinopia_hostname }}.{{ domainname }}; # $host;
        proxy_set_header            X-Url-Scheme    $scheme;
        proxy_set_header            X-Host          $http_host;
        proxy_set_header            X-Real-IP       $remote_addr;
        proxy_set_header            X-Forwarded-For $proxy_add_x_forwarded_for;
        proxy_set_header            Proxy-host      $proxy_host;
        proxy_buffering             off;
        proxy_connect_timeout       7200;
        proxy_send_timeout          7200;
        proxy_read_timeout          7200;
        proxy_buffers               8 32k;
        client_max_body_size        0;
        client_body_buffer_size     128k;

    }
}
```

**Comment by Deadleg** [comment]
This no longer causes an error with the above configuration (don't know when it fixed itself).
