### ISSUE TITLE
null item from contributor net.ishchenko.idea.nginx.NginxChooseByNameContributor@767cf14b for name nginx.conf~ [Plugin: ideanginx9]: null item from contributor net.ishchenko.idea.nginx.NginxChooseByNameContributor@767cf14b for name nginx.conf~ [Plugin: id

### ISSUE THREAD

**Issue by natros** [ishchenko/idea-nginx#12]
```
null item from contributor net.ishchenko.idea.nginx.NginxChooseByNameContributor@767cf14b for name nginx.conf~ [Plugin: ideanginx9]: null item from contributor net.ishchenko.idea.nginx.NginxChooseByNameContributor@767cf14b for name nginx.conf~ [Plugin: ideanginx9]
com.intellij.diagnostic.PluginException: null item from contributor net.ishchenko.idea.nginx.NginxChooseByNameContributor@767cf14b for name nginx.conf~ [Plugin: ideanginx9]
    at com.intellij.ide.util.gotoByName.ContributorsBasedGotoByModel$3.process(ContributorsBasedGotoByModel.java:227)
    at com.intellij.ide.util.gotoByName.ContributorsBasedGotoByModel$3.process(ContributorsBasedGotoByModel.java:192)
    at com.intellij.concurrency.ApplierCompleter.a(ApplierCompleter.java:119)
    at com.intellij.concurrency.ApplierCompleter.access$000(ApplierCompleter.java:42)
    at com.intellij.concurrency.ApplierCompleter$1.run(ApplierCompleter.java:82)
    at com.intellij.openapi.application.impl.ApplicationImpl.tryRunReadAction(ApplicationImpl.java:1166)
    at com.intellij.concurrency.ApplierCompleter$2.run(ApplierCompleter.java:91)
    at com.intellij.openapi.progress.ProgressManager.executeProcessUnderProgress(ProgressManager.java:209)
    at com.intellij.openapi.progress.impl.ProgressManagerImpl.executeProcessUnderProgress(ProgressManagerImpl.java:212)
    at com.intellij.concurrency.ApplierCompleter.a(ApplierCompleter.java:103)
    at com.intellij.concurrency.ApplierCompleter.compute(ApplierCompleter.java:79)
    at jsr166e.CountedCompleter.exec(CountedCompleter.java:684)
    at jsr166e.ForkJoinTask.doExec(ForkJoinTask.java:260)
    at jsr166e.ForkJoinPool$WorkQueue.runTask(ForkJoinPool.java:858)
    at jsr166e.ForkJoinPool.scan(ForkJoinPool.java:1687)
    at jsr166e.ForkJoinPool.runWorker(ForkJoinPool.java:1642)
    at jsr166e.ForkJoinWorkerThread.run(ForkJoinWorkerThread.java:109)

Intellij IDEA 13 132.719
```

**Comment by Deadleg** [comment]
Closing due to age.
