### ISSUE TITLE
Error while indexing - _NginxLexer: Error: pushback value was too large

### ISSUE THREAD

**Issue by azder** [ishchenko/idea-nginx#18]
```
    Error while indexing /xxxx/xxxx/some-nginx-config-file
    To reindex this file IDEA has to be restarted: net.ishchenko.idea.nginx.lexer._NginxLexer: Error: pushback value was too large
    java.lang.Error: net.ishchenko.idea.nginx.lexer._NginxLexer: Error: pushback value was too large
        at net.ishchenko.idea.nginx.lexer._NginxLexer.zzScanError(_NginxLexer.java:435)
        at net.ishchenko.idea.nginx.lexer._NginxLexer.yypushback(_NginxLexer.java:449)
        at net.ishchenko.idea.nginx.lexer._NginxLexer.advance(_NginxLexer.java:592)
        at com.intellij.lexer.FlexAdapter.locateToken(FlexAdapter.java:95)
        at com.intellij.lexer.FlexAdapter.getTokenType(FlexAdapter.java:58)
        at com.intellij.openapi.editor.ex.util.LexerEditorHighlighter.a(LexerEditorHighlighter.java:312)
        at com.intellij.openapi.editor.ex.util.LexerEditorHighlighter.setText(LexerEditorHighlighter.java:293)
        at com.intellij.psi.impl.cache.impl.id.PlatformIdTableBuilding$TokenSetTodoIndexer.map(PlatformIdTableBuilding.java:167)
        at com.intellij.psi.impl.cache.impl.id.PlatformIdTableBuilding$TokenSetTodoIndexer.map(PlatformIdTableBuilding.java:144)
        at com.intellij.psi.impl.cache.impl.todo.TodoIndex$4.map(TodoIndex.java:101)
        at com.intellij.psi.impl.cache.impl.todo.TodoIndex$4.map(TodoIndex.java:93)
        at com.intellij.util.indexing.MapReduceIndex.update(MapReduceIndex.java:215)
        at com.intellij.util.indexing.FileBasedIndexImpl.a(FileBasedIndexImpl.java:1820)
        at com.intellij.util.indexing.FileBasedIndexImpl.a(FileBasedIndexImpl.java:1747)
        at com.intellij.util.indexing.FileBasedIndexImpl.access$5100(FileBasedIndexImpl.java:98)
        at com.intellij.util.indexing.FileBasedIndexImpl$ChangedFilesCollector.a(FileBasedIndexImpl.java:2320)
        at com.intellij.util.indexing.FileBasedIndexImpl$ChangedFilesCollector.access$2900(FileBasedIndexImpl.java:1924)
        at com.intellij.util.indexing.FileBasedIndexImpl.processRefreshedFile(FileBasedIndexImpl.java:1700)
        at com.intellij.util.indexing.FileBasedIndexProjectHandler$RefreshCacheUpdater.processFile(FileBasedIndexProjectHandler.java:131)
        at com.intellij.openapi.project.CacheUpdateSession.processFile(CacheUpdateSession.java:103)
        at com.intellij.openapi.project.CacheUpdateRunner$MyRunnable$1.run(CacheUpdateRunner.java:231)
        at com.intellij.openapi.project.CacheUpdateRunner$MyRunnable$2.run(CacheUpdateRunner.java:244)
        at com.intellij.openapi.progress.impl.ProgressManagerImpl$2.run(ProgressManagerImpl.java:178)
        at com.intellij.openapi.progress.ProgressManager.executeProcessUnderProgress(ProgressManager.java:209)
        at com.intellij.openapi.progress.impl.ProgressManagerImpl.executeProcessUnderProgress(ProgressManagerImpl.java:212)
        at com.intellij.openapi.progress.impl.ProgressManagerImpl.runProcess(ProgressManagerImpl.java:171)
        at com.intellij.openapi.project.CacheUpdateRunner$MyRunnable.run(CacheUpdateRunner.java:236)
        at com.intellij.openapi.project.CacheUpdateRunner$4.run(CacheUpdateRunner.java:273)
        at com.intellij.openapi.application.impl.ApplicationImpl$8.run(ApplicationImpl.java:419)
        at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:471)
        at java.util.concurrent.FutureTask.run(FutureTask.java:262)
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1145)
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:615)
        at java.lang.Thread.run(Thread.java:745)
        at com.intellij.openapi.application.impl.ApplicationImpl$1$1.run(ApplicationImpl.java:149)
```

**Comment by Deadleg** [comment]
Closing due to age.
