### ISSUE TITLE
Error when opening drools source code 

### ISSUE THREAD

**Issue by relgames** [ishchenko/idea-nginx#19]
When I open https://github.com/droolsjbpm/drools in IDEA, I get an exception from nginx plugin:

```
Error while indexing /home/oleg/work/drools/drools-core/src/test/resources/META-INF/WorkItemHandlers1.conf
To reindex this file IDEA has to be restarted: chars.length:0, start:0, end:180
java.lang.IndexOutOfBoundsException: chars.length:0, start:0, end:180
    at com.intellij.util.text.CharArrayCharSequence.<init>(CharArrayCharSequence.java:32)
    at com.intellij.util.text.CharArrayCharSequence.subSequence(CharArrayCharSequence.java:53)
    at net.ishchenko.idea.nginx.lexer._NginxLexer.yytext(_NginxLexer.java:384)
    at net.ishchenko.idea.nginx.lexer._NginxLexer.advance(_NginxLexer.java:555)
    at com.intellij.lexer.FlexAdapter.locateToken(FlexAdapter.java:95)
    at com.intellij.lexer.FlexAdapter.getTokenType(FlexAdapter.java:58)
    at com.intellij.openapi.editor.ex.util.LexerEditorHighlighter.a(LexerEditorHighlighter.java:312)
    at com.intellij.openapi.editor.ex.util.LexerEditorHighlighter.setText(LexerEditorHighlighter.java:293)
    at com.intellij.psi.impl.cache.impl.id.PlatformIdTableBuilding$TokenSetTodoIndexer.map(PlatformIdTableBuilding.java:167)
    at com.intellij.psi.impl.cache.impl.id.PlatformIdTableBuilding$TokenSetTodoIndexer.map(PlatformIdTableBuilding.java:144)
    at com.intellij.psi.impl.cache.impl.todo.TodoIndex$4.map(TodoIndex.java:101)
    at com.intellij.psi.impl.cache.impl.todo.TodoIndex$4.map(TodoIndex.java:93)
    at com.intellij.util.indexing.MapReduceIndex.update(MapReduceIndex.java:215)
    at com.intellij.util.indexing.FileBasedIndexImpl.a(FileBasedIndexImpl.java:1824)
    at com.intellij.util.indexing.FileBasedIndexImpl.a(FileBasedIndexImpl.java:1751)
    at com.intellij.util.indexing.FileBasedIndexImpl.indexFileContent(FileBasedIndexImpl.java:1714)
    at com.intellij.util.indexing.UnindexedFilesUpdater.processFile(UnindexedFilesUpdater.java:73)
    at com.intellij.openapi.project.CacheUpdateSession.processFile(CacheUpdateSession.java:103)
    at com.intellij.openapi.project.CacheUpdateRunner$MyRunnable$1.run(CacheUpdateRunner.java:231)
    at com.intellij.openapi.application.impl.ApplicationImpl.runReadAction(ApplicationImpl.java:911)
    at com.intellij.openapi.project.CacheUpdateRunner$MyRunnable$2.run(CacheUpdateRunner.java:241)
    at com.intellij.openapi.progress.impl.ProgressManagerImpl$2.run(ProgressManagerImpl.java:178)
    at com.intellij.openapi.progress.ProgressManager.executeProcessUnderProgress(ProgressManager.java:209)
    at com.intellij.openapi.progress.impl.ProgressManagerImpl.executeProcessUnderProgress(ProgressManagerImpl.java:212)
    at com.intellij.openapi.progress.impl.ProgressManagerImpl.runProcess(ProgressManagerImpl.java:171)
    at com.intellij.openapi.project.CacheUpdateRunner$MyRunnable.run(CacheUpdateRunner.java:236)
    at com.intellij.openapi.application.impl.ApplicationImpl$8.run(ApplicationImpl.java:419)
    at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:471)
    at java.util.concurrent.FutureTask.run(FutureTask.java:262)
    at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1145)
    at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:615)
    at java.lang.Thread.run(Thread.java:745)
    at com.intellij.openapi.application.impl.ApplicationImpl$1$1.run(ApplicationImpl.java:149)
```

**Comment by Deadleg** [comment]
That specific fine is not an nginx file, but it looks like you might have *.conf as nginx files.
