### ISSUE TITLE
Plugin crash in Idea 11.1.4 on OSX 10.8.2

### ISSUE THREAD

**Issue by 91koff** [ishchenko/idea-nginx#5]
Error while indexing 
{path to file.conf}
To reindex this file IDEA has to be restarted: net.ishchenko.idea.nginx.lexer._NginxLexer: Error: could not match input
java.lang.Error: net.ishchenko.idea.nginx.lexer._NginxLexer: Error: could not match input
    at net.ishchenko.idea.nginx.lexer._NginxLexer.zzScanError(_NginxLexer.java:431)
    at net.ishchenko.idea.nginx.lexer._NginxLexer.advance(_NginxLexer.java:610)
    at com.intellij.lexer.FlexAdapter.locateToken(FlexAdapter.java:93)
    at com.intellij.lexer.FlexAdapter.advance(FlexAdapter.java:75)
    at com.intellij.openapi.editor.ex.util.LexerEditorHighlighter.a(LexerEditorHighlighter.java:316)
    at com.intellij.openapi.editor.ex.util.LexerEditorHighlighter.setText(LexerEditorHighlighter.java:291)
    at com.intellij.psi.impl.cache.impl.id.IdTableBuilding$TokenSetTodoIndexer.map(IdTableBuilding.java:331)
    at com.intellij.psi.impl.cache.impl.id.IdTableBuilding$TokenSetTodoIndexer.map(IdTableBuilding.java:308)
    at com.intellij.psi.impl.cache.impl.todo.TodoIndex$4.map(TodoIndex.java:106)
    at com.intellij.psi.impl.cache.impl.todo.TodoIndex$4.map(TodoIndex.java:99)
    at com.intellij.util.indexing.MapReduceIndex.update(MapReduceIndex.java:215)
    at com.intellij.util.indexing.FileBasedIndex$24.run(FileBasedIndex.java:1660)
    at com.intellij.openapi.progress.impl.ProgressManagerImpl.executeNonCancelableSection(ProgressManagerImpl.java:136)
    at com.intellij.util.indexing.FileBasedIndex.a(FileBasedIndex.java:1656)
    at com.intellij.util.indexing.FileBasedIndex.indexFileContent(FileBasedIndex.java:1621)
    at com.intellij.util.indexing.UnindexedFilesUpdater.processFile(UnindexedFilesUpdater.java:64)
    at com.intellij.openapi.project.CacheUpdateSession.processFile(CacheUpdateSession.java:102)
    at com.intellij.openapi.project.CacheUpdateRunner$MyRunnable$1.run(CacheUpdateRunner.java:228)
    at com.intellij.openapi.application.impl.ApplicationImpl.runReadAction(ApplicationImpl.java:864)
    at com.intellij.openapi.project.CacheUpdateRunner$MyRunnable.run(CacheUpdateRunner.java:232)
    at com.intellij.openapi.application.impl.ApplicationImpl$6.run(ApplicationImpl.java:434)
    at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:439)
    at java.util.concurrent.FutureTask$Sync.innerRun(FutureTask.java:303)
    at java.util.concurrent.FutureTask.run(FutureTask.java:138)
    at java.util.concurrent.ThreadPoolExecutor$Worker.runTask(ThreadPoolExecutor.java:886)
    at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:908)
    at java.lang.Thread.run(Thread.java:680)
    at com.intellij.openapi.application.impl.ApplicationImpl$1$1.run(ApplicationImpl.java:145)

**Comment by Deadleg** [comment]
No longer seems to be an issue with the above config.
