### ISSUE TITLE
Null item exception

### ISSUE THREAD

**Issue by syabro** [ishchenko/idea-nginx#51]
```
ull item from contributor net.ishchenko.idea.nginx.NginxChooseByNameContributor@3cad7985 for name .DS_Store [Plugin: ideanginx9]
com.intellij.diagnostic.PluginException: null item from contributor net.ishchenko.idea.nginx.NginxChooseByNameContributor@3cad7985 for name .DS_Store [Plugin: ideanginx9]
	at com.intellij.ide.util.gotoByName.ContributorsBasedGotoByModel.a(ContributorsBasedGotoByModel.java:218)
	at com.intellij.concurrency.ApplierCompleter.a(ApplierCompleter.java:123)
	at com.intellij.openapi.application.impl.ApplicationImpl.tryRunReadAction(ApplicationImpl.java:1033)
	at com.intellij.concurrency.ApplierCompleter.b(ApplierCompleter.java:96)
	at com.intellij.openapi.progress.impl.CoreProgressManager.a(CoreProgressManager.java:494)
	at com.intellij.openapi.progress.impl.CoreProgressManager.executeProcessUnderProgress(CoreProgressManager.java:443)
	at com.intellij.openapi.progress.impl.ProgressManagerImpl.executeProcessUnderProgress(ProgressManagerImpl.java:54)
	at com.intellij.concurrency.ApplierCompleter.a(ApplierCompleter.java:106)
	at com.intellij.concurrency.ApplierCompleter.compute(ApplierCompleter.java:91)
	at java.util.concurrent.CountedCompleter.exec(CountedCompleter.java:731)
	at java.util.concurrent.ForkJoinTask.doExec(ForkJoinTask.java:289)
	at java.util.concurrent.ForkJoinPool.helpComplete(ForkJoinPool.java:1870)
	at java.util.concurrent.ForkJoinPool.externalHelpComplete(ForkJoinPool.java:2467)
	at java.util.concurrent.ForkJoinTask.externalAwaitDone(ForkJoinTask.java:324)
	at java.util.concurrent.ForkJoinTask.doJoin(ForkJoinTask.java:391)
	at java.util.concurrent.ForkJoinTask.join(ForkJoinTask.java:719)
	at java.util.concurrent.ForkJoinPool.invoke(ForkJoinPool.java:2616)
	at com.intellij.concurrency.JobLauncherImpl.invokeConcurrentlyUnderProgress(JobLauncherImpl.java:60)
	at com.intellij.concurrency.JobLauncher.invokeConcurrentlyUnderProgress(JobLauncher.java:57)
	at com.intellij.ide.util.gotoByName.ContributorsBasedGotoByModel.getElementsByName(ContributorsBasedGotoByModel.java:244)
	at com.intellij.ide.util.gotoByName.DefaultChooseByNameItemProvider.filterElements(DefaultChooseByNameItemProvider.java:146)
	at com.intellij.ide.actions.GotoFileItemProvider.filterElements(GotoFileItemProvider.java:74)
	at com.intellij.ide.util.gotoByName.ChooseByNameBase$CalcElementsThread.a(ChooseByNameBase.java:1565)
	at com.intellij.ide.util.gotoByName.ChooseByNameBase$CalcElementsThread.a(ChooseByNameBase.java:1544)
	at com.intellij.ide.util.gotoByName.ChooseByNameBase$CalcElementsThread.performInReadAction(ChooseByNameBase.java:1520)
	at com.intellij.openapi.progress.util.ReadTask$1.compute(ReadTask.java:70)
	at com.intellij.openapi.progress.util.ReadTask$1.compute(ReadTask.java:67)
	at com.intellij.openapi.application.impl.ApplicationImpl.runReadAction(ApplicationImpl.java:870)
	at com.intellij.openapi.progress.util.ReadTask.runBackgroundProcess(ReadTask.java:67)
	at com.intellij.ide.util.gotoByName.ChooseByNameBase$CalcElementsThread.runBackgroundProcess(ChooseByNameBase.java:1508)
	at com.intellij.openapi.progress.util.ProgressIndicatorUtils.a(ProgressIndicatorUtils.java:213)
	at com.intellij.openapi.progress.impl.CoreProgressManager$4.run(CoreProgressManager.java:190)
	at com.intellij.openapi.progress.impl.CoreProgressManager$3.run(CoreProgressManager.java:170)
	at com.intellij.openapi.progress.impl.CoreProgressManager.a(CoreProgressManager.java:494)
	at com.intellij.openapi.progress.impl.CoreProgressManager.executeProcessUnderProgress(CoreProgressManager.java:443)
	at com.intellij.openapi.progress.impl.ProgressManagerImpl.executeProcessUnderProgress(ProgressManagerImpl.java:54)
	at com.intellij.openapi.progress.impl.CoreProgressManager.runProcess(CoreProgressManager.java:155)
	at com.intellij.openapi.progress.impl.CoreProgressManager.runProcess(CoreProgressManager.java:187)
	at com.intellij.openapi.progress.util.ProgressIndicatorUtils.a(ProgressIndicatorUtils.java:211)
	at com.intellij.openapi.progress.util.ProgressIndicatorUtils.access$000(ProgressIndicatorUtils.java:44)
	at com.intellij.openapi.progress.util.ProgressIndicatorUtils$4.run(ProgressIndicatorUtils.java:179)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
	at java.lang.Thread.run(Thread.java:745)
```

**Comment by Deadleg** [comment]
Reproduction steps? I can't haven't had any problems with .DS_Store files on OSX.

**Comment by syabro** [comment]
@Deadleg nope :/
Just open my pycharm and have this :(

**Comment by syabro** [comment]
looks like it disappeared :) closing :)
